version: '3.8'
services:
  server:
    image: ${DOCKER_USERNAME}/kimgreen
    ports:
      -8080:8080
    restart: always
    environment:
      DATASOURCE_URL_RDS=${DATASOURCE_URL_RDS}
      DATASOURCE_USERNAME_RDS=${DATASOURCE_USERNAME_RDS}
      DATASOURCE_PASSWORD_RDS=${DATASOURCE_PASSWORD_RDS}
      jwt.secret-key=${jwt.secret-key}
      aws.credentials.access-key=${aws.credentials.access-key}
      aws.credentials.secret-key=${aws.credentials.secret-key}
      aws.region.static=${aws.region.static}
      aws.s3.bucket=${aws.s3.bucket}
      fcm.url=${fcm.url}
      TZ=Asia/Seoul
    env_file:
      - .env



# docker run -d --name server -e TZ=Asia/Seoul -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/kimgreen
