version: '3.8'
services:
  server:
    image: ${DOCKER_USERNAME}/kimgreen
    ports:
      -8080:8080
    restart: always
    environment:
      DATASOURCE_URL_RDS=${DATASOURCE_URL_RDS}
      DATASOURCE_USERNAME_RDS=${DATASOURCE_USERNAME_RDS}
      DATASOURCE_PASSWORD_RDS=${DATASOURCE_PASSWORD_RDS}
      JWT_SECRET_KEY=${JWT_SECRET_KEY}
      AWS_CREDENTIALS_ACCESS_KEY=${AWS_CREDENTIALS_ACCESS_KEY}
      AWS_CREDENTIALS_SECRET_KEY=${AWS_CREDENTIALS_SECRET_KEY}
      AWS_REGION_STATIC=${AWS_REGION_STATIC}
      AWS_S3_BUCKET=${AWS_S3_BUCKET}
      FCM_URL=${FCM_URL}
      TZ=Asia/Seoul
    env_file:
      - .env



# docker run -d --name server -e TZ=Asia/Seoul -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/kimgreen